<div class="startWrap">
    <div>
        <img src="/images/DSC_8188.jpg" class="rightblock">
        <p>
        <p class="title">Share photos with other people</p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam asperiores consequatur consequuntur dignissimos impedit ipsam ipsum labore laboriosam laudantium magni mollitia nihil nisi odit, officia optio quas rem repellat, velit vitae. Accusantium aliquam animi autem consectetur cum delectus, deleniti exercitationem incidunt iure labore maiores nam nesciunt nihil numquam porro possimus quas quidem, velit! Ab autem cupiditate et incidunt mollitia officia placeat recusandae rem. Ab aliquam animi deserunt expedita natus quas repellat. Assumenda aut, culpa delectus dignissimos eaque, iusto, neque numquam obcaecati officia officiis pariatur praesentium quaerat quas quia saepe sequi vero voluptatibus? A aperiam atque deserunt distinctio dolor dolore dolorem dolorum eius, eum facere modi molestias nostrum odit optio pariatur quasi qui, quidem, reiciendis rerum sit temporibus velit voluptatem. Aliquam animi aperiam, assumenda culpa cumque deserunt eos ex fuga harum ipsam iusto laborum non praesentium provident quae quas qui reiciendis tenetur totam velit veritatis vero voluptas! Doloremque facere harum impedit in laudantium nemo nesciunt nulla obcaecati quae quas quisquam, quod rem repellat sed totam veniam voluptatum? A ad aperiam assumenda, consectetur esse in ipsam nobis, nulla porro provident quibusdam sequi sunt voluptatibus! A aliquid, architecto commodi eius eos exercitationem ipsa iusto placeat provident qui quia repudiandae, sed voluptate voluptatem.</p>
    </div>
    <br><br><br><br>
    <div>
        <img src="/images/DSC_8190.jpg" class="leftblock">
        <p>
        <p class="title">See photos from all over the world</p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam asperiores consequatur consequuntur dignissimos impedit ipsam ipsum labore laboriosam laudantium magni mollitia nihil nisi odit, officia optio quas rem repellat, velit vitae. Accusantium aliquam animi autem consectetur cum delectus, deleniti exercitationem incidunt iure labore maiores nam nesciunt nihil numquam porro possimus quas quidem, velit! Ab autem cupiditate et incidunt mollitia officia placeat recusandae rem. Ab aliquam animi deserunt expedita natus quas repellat. Assumenda aut, culpa delectus dignissimos eaque, iusto, neque numquam obcaecati officia officiis pariatur praesentium quaerat quas quia saepe sequi vero voluptatibus? A aperiam atque deserunt distinctio dolor dolore dolorem dolorum eius, eum facere modi molestias nostrum odit optio pariatur quasi qui, quidem, reiciendis rerum sit temporibus velit voluptatem. Aliquam animi aperiam, assumenda culpa cumque deserunt eos ex fuga harum ipsam iusto laborum non praesentium provident quae quas qui reiciendis tenetur totam velit veritatis vero voluptas! Doloremque facere harum impedit in laudantium nemo nesciunt nulla obcaecati quae quas quisquam, quod rem repellat sed totam veniam voluptatum? A ad aperiam assumenda, consectetur esse in ipsam nobis, nulla porro provident quibusdam sequi sunt voluptatibus! A aliquid, architecto commodi eius eos exercitationem ipsa iusto placeat provident qui quia repudiandae, sed voluptate voluptatem.</p>
    </div>
</div>